### ISSUE TITLE
Default directory

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Shelf-Desktop#14]
In case when no path provided for the link storage, `$HOME/.ark-shelf` must be used.

**UP:** This must be a root folder, i.e. it would contain `.ark` subfolder with metadata.

**Comment by mberry** [comment]
Spoken about using the platform defaults instead elsewhere but otherwise this is a quick change from the current folder layout:

![image](https://github.com/ARK-Builders/ARK-Shelf-Desktop/assets/17392435/faf10178-904a-446d-ae90-effeaa0eb984)

I'd also say drop the `.ark` as a hidden folder or perhaps even altogether as it doesn't really serve much purpose

**Comment by kirillt** [comment]
@mberry `.ark` subfolder is essential at the moment since it allows us to sync user metadata to other devices.. Technically, user might have different folders with different links, each one should contain `.ark` subfolder. These folders are used as indicators of user folders on mobile, during filesystem scanning. We might get rid of the hidden subfolder when we implement syncing library. So far we just utilize Syncthing as imitation of it, it works with files only, so we create `.ark` folder right next to the data itself because user can choose syncing only that folder.

Sorry, I haven't mentioned this before. The issue is about location of the folder for storing links itself.

> $HOME/.ark-shelf

This folder was suggested for the case when user doesn't really care about syncing etc. If nothing is specified, we need to use some default location. But we must allow user override this choice. The problem is that in `main` links are stored in the working dir of the calling process.
